# Generated by Django 5.1.2 on 2024-11-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalWebsite', '0002_artproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproject',
            name='image',
            field=models.ImageField(upload_to='static/images/art_projects/'),
        ),
        migrations.AlterField(
            model_name='codeproject',
            name='image',
            field=models.ImageField(upload_to='static/images/code_projects/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='static/images/testimonials/'),
        ),
    ]
