# Generated by Django 5.1.2 on 2024-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalWebsite', '0003_alter_artproject_image_alter_codeproject_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artproject',
            name='url',
        ),
        migrations.AddField(
            model_name='artproject',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
