# Generated by Django 5.1.4 on 2025-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalWebsite', '0006_artproject_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textfiled',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
